import os
from playsound import playsound 
# MEET  VORA
# SAPID-60003200095
''' NOTES ARE THERE IN CODE WITH HAARY'S PDF(IN NEW VOLUME F PYTHON WALA FOLDER) 
THE ONE WHICH ARENT THERE ARE WRITTEN DOWN IN THE 
PROGRAMMING LANGUAGE WALA BOOK SO REFER THAT BOOK FOR MORE   
'''
print("1ST PROBLEM STATEMENT") #FOR ONE LINER CODE USE DOUBLE QUOTES

print('''Baby shark doo doo doo doo doo doo
Baby shark doo doo doo doo doo doo
Baby shark doo doo doo doo doo doo
Baby shark''') # FOR MULTI LINE CODE USE TRIPPLE QUOTES

print("2ND PROBLEM STATEMENT") #DONE ON WINDOWS POWERSHELL

print("3RD PROBLEM STATEMENT") #DOWNLOADED PLAYSOUND WHICH IS USED FOR MP3 SOUNDS
print("DIND'T HAPPEN NEED TO DISCUSS WITH SOMEONE")  

print("4TH PROBLEM STATEMENT") #USED LISTDIR() WHOOSE FUNCTIONS WILL BE BRIEFED LATER IN THE FURHTER CHAPTERS

print("5TH PROBLEM STATEMENT") #DONE


